@echo off
setlocal enabledelayedexpansion

REM Input URL
set "url=%~1"

REM Check if URL is provided
if "%url%"=="" (
    echo Usage: %~nx0 [URL]
    exit /b 1
)

REM Use curl to check URL validity
for /f "tokens=2 delims=: " %%A in ('curl -o nul -s -w "HTTPSTATUS:%%{http_code}" "!url!"') do (
    set "status=%%A"
)

REM Check the status code
if "%status%"=="200" (
    echo Node.js server is running.
	@echo off
	powershell -Command "Write-EventLog -LogName 'WiConnectLogs' -Source 'WiConnectApp' -EntryType Information -EventId 1001 -Message 'Server is Running'"
	
     exit /b 0
) else (
    REM Define the server directory and entry file
   
    

    REM Navigate to the server directory
    cd /d "%serverDir%"

    REM Get the current date and time
    for /f "tokens=2 delims==" %%A in ('wmic os get localdatetime /value') do set "datetime=%%A"
    set "formattedDate=!datetime:~0,4!-!datetime:~4,2!-!datetime:~6,2!"
    set "formattedTime=!datetime:~8,2!:!datetime:~10,2!:!datetime:~12,2!"

   
    
    REM start /min cmd /c "C:\Witron\Node\WiConnect App\npm.cmd start"
	start cmd /c "cd /d C:\Witron\Node\WiConnect App && npm start"

	echo Starting Node.js server at !formattedDate! !formattedTime!...
    REM Log to Windows Event Viewer
	powershell -Command "Write-EventLog -LogName 'WiConnectLogs' -Source 'WiConnectApp' -EntryType Information -EventId 1001 -Message 'Node.js server started at !formattedDate! !formattedTime!'"
	REM send notification
	set "appPath=%~dp0"
	set scriptPath=ServerStartedNotification.ps1
	set PowerShellScriptPath= %appPath%%scriptPath%
	:: Set the Reports variable as an array of file paths
	::smtpserver
	set SmtpServer="10.155.199.1"
	::email configs
	set EmailFrom="WiConnectAppCalgary@sobeys.com"
	set EmailTo="framos@witron.com;fgomez@witron.com"
	set SubjectLine="Node.js WiConnectApp Server Started"

	set emailBody="This notification was generated by the schedule taak whenever the node js server got stopped."
	::echo %Reports% 
	powershell.exe -ExecutionPolicy Bypass -File %PowerShellScriptPath% -smtpServer %SmtpServer% -from %EmailFrom% -to %EmailTo% -subject %SubjectLine% -body %emailBody%
	
	)

exit /b 0
